# Generated by Django 2.0.1 on 2018-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name='last time checked'),
        ),
        migrations.AlterField(
            model_name='website',
            name='last_status',
            field=models.IntegerField(null=True, verbose_name='last status checked'),
        ),
    ]
