# Generated by Django 2.0.1 on 2018-01-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_auto_20180121_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='name',
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=75, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='website',
            name='user_id',
            field=models.CharField(max_length=30, verbose_name='Telegram user id'),
        ),
    ]
