# Generated by Django 2.0.1 on 2018-01-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20180121_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(default=0, max_length=30, verbose_name='Telegram chat id'),
            preserve_default=False,
        ),
    ]
