# Generated by Django 2.0.1 on 2018-01-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_checked',
            field=models.DateTimeField(null=True, verbose_name='last time checked'),
        ),
        migrations.AddField(
            model_name='website',
            name='wrong_count',
            field=models.IntegerField(null=True, verbose_name='count wrong checked'),
        ),
        migrations.AlterField(
            model_name='website',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name='last time seen ok'),
        ),
    ]
