# Generated by Django 2.0.1 on 2018-01-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0007_auto_20180122_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chat_disabled',
            field=models.IntegerField(default=1, verbose_name='if chat is disabled'),
        ),
    ]
